---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.1
  - name: ansible.windows
    version: 3.3.0
  - name: community.general
    version: 12.1.0
  - name: community.sops
    version: 2.2.7
  - name: community.windows
    version: 3.1.0
  # https://github.com/kewlfft/ansible-aur
  - name: kewlfft.aur
