---
collections:
  - name: ansible.posix
    version: 2.1.0
  - name: ansible.utils
    version: 6.0.0
  - name: ansible.windows
    version: 3.2.0
  - name: community.general
    version: 11.4.2
  - name: community.sops
    version: 2.2.7
  - name: community.windows
    version: 3.0.1
  # https://github.com/kewlfft/ansible-aur
  - name: kewlfft.aur
